name: INDI package builder for jetson Nano
on:
  workflow_dispatch:

env:
  APT_PUBKEY_PATH: indi-jetson-nano-keyring.asc

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build packages on Ubuntu 18.04 ARM64 image
        run: >
          docker run --rm -v $PWD:/usr/src/ alxgomz/indi-builder:2.1.3

      - name: Get APT repo public key
        id: apt_pub_key
        run: |
          echo 'pem<<EOT' >> $GITHUB_OUTPUT
          cat "$APT_PUBKEY_PATH" >> $GITHUB_OUTPUT
          echo EOT >> $GITHUB_OUTPUT

      - uses: smeinecke/apt-repo-action@v2.1.6
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: arm64
          repo_supported_version: bionic
          file: |
            *.deb
            indi-3rdparty/*.deb
          file_target_version: bionic
          private_key: ${{ secrets.APT_PRIV_KEY }}
          public_key: ${{ steps.apt_pub_key.outputs.pem }}
          key_passphrase: ${{ secrets.APT_KEY_PASSPHRASE }}
          page_branch: debs
