name: INDI Docker build env
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
      - .github/workflows/docker-build.yml

env:
  DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKER_IMAGE: indi-builder
  DOCKER_TAG: 2.3.0

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
